### ISSUE TITLE
Cannot identify which pins are being utilized?

### ISSUE THREAD

**Issue by brenly** [hideakitai/TCS34725#5]
Hello, this code is fantastic and very simple but I need software comments saying which pins are initialized by default?
it ran immediately out of the box, but i cannot figure out which pins to attach. the rest of the documentation makes perfect sense.
Just 3 lines of comments would go a very long way to making this much more user friendly. Thank you.

**Comment by hideakitai** [comment]
I can't specify the default pins because I2C pins are vary depending on the board. Please refer to your board's guide.
