### ISSUE TITLE
ERROR: TCS34725 NOT FOUND !!!

### ISSUE THREAD

**Issue by circuit-activebuildings** [hideakitai/TCS34725#6]
After trying out the Example Code, it gives error "ERROR: TCS34725 NOT FOUND !!!".
this issue get resolved when you try Adafruit's library first and then after this. So there must be some pending initialisation in this code.

**Comment by hideakitai** [comment]
I think the connection is unstable or too fast to start i2c. Please insert delay() before `if (!tcs.attach(Wire))`

**Comment by JasperB-PC** [comment]
I seem to be having the same issue, it did not resolve by installing other library's or inserting a delay. It worked for a while and without seemingly doing anything between two tests it stopped working and printed the error message. I am working with a lattepanda delta 3 with an integrated arduino leonardo. I already tested with another sensor but the same problem arises. When I run an I2C address checker it does still find the sensor and prints the right address. The sensor I am using is the TCS3472. Does anybody know a fix?
