### ISSUE TITLE
Device Not found

### ISSUE THREAD

**Issue by jimtal001** [hideakitai/TCS34725#7]
I saw this same problem in your **closed issues**, but I wanted to ask if you might have any other possible fixes.

Some Information:
1. I'm using the latest version of your library in Arduino IDE 2.3.2
2. Scanning for the I2C Address is successful.  
3. Adding the delay before **if (!tcs.attach(Wire))** did not help.  
4. The arduino library works fine.
5. I have tried multiple sensors with same results.

**Comment by hideakitai** [comment]
Which I2C address did you find? 0x29? Please confirm the address is 0x29.

![image](https://github.com/hideakitai/TCS34725/assets/889950/8257e0cf-ed22-4ad6-9c4b-4baebd910800)

Also, `attach()` checks if the `ID` register is `0x44`. Please confirm your device is TCS34725.

![image](https://github.com/hideakitai/TCS34725/assets/889950/5117bd39-b78b-4cb7-80fb-602c7edfd247)

**Comment by jimtal001** [comment]
The I2C Address being reported is 0x29. 
you stated: "Also, attach() checks if the ID register is 0x44. Please confirm your device is TCS34725." 
I have not found any example code of using attach().  Can you demonstrate?

This is the link to the device: 
https://www.amazon.com/dp/B0CW9PQPYX?psc=1&ref=ppx_yo2ov_dt_b_product_details

**Comment by hideakitai** [comment]
example code not found? here

https://github.com/hideakitai/TCS34725/blob/5b6066b0c44d450e9c427e9eebf21a29855d75c6/example/example.ino#L10

**Comment by hideakitai** [comment]
Your device may not be TCS34725

**Comment by hideakitai** [comment]
If you still need help, please reopen this issue.

**Comment by hideakitai** [comment]
If you still need help, please reopen this issue.
